from AthenaCommon.DetFlags import DetFlags
DetFlags.ID_setOn()
DetFlags.TRT_setOff()
DetFlags.detdescr.TRT_setOff()
DetFlags.makeRIO.TRT_setOff()
DetFlags.BCM_setOff()
DetFlags.detdescr.BCM_setOff()
DetFlags.makeRIO.BCM_setOff()
DetFlags.DBM_setOff()
DetFlags.detdescr.DBM_setOff()
DetFlags.makeRIO.DBM_setOff()
DetFlags.Calo_setOff()
DetFlags.MBTS_setOff()
DetFlags.detdescr.MBTS_setOff()
DetFlags.makeRIO.MBTS_setOff()
DetFlags.Muon_setOff()
DetFlags.Truth_setOn()
DetFlags.HEC_setOff()
DetFlags.FCal_setOff()
DetFlags.Tile_setOff()
DetFlags.MDT_setOff()
DetFlags.CSC_setOff()
DetFlags.TGC_setOff()
DetFlags.RPC_setOff()
DetFlags.sTGC_setOff()
DetFlags.LAr_setOff()
DetFlags.Tile_setOff()
DetFlags.overlay.all_setOff()
DetFlags.digitize.all_setOff()
DetFlags.digitize.pixel_setOn()
DetFlags.digitize.SCT_setOn()
print("Here are the Det Flags")
DetFlags.Print()

