export postIncludeITk="InDetSLHC_Example/postInclude.SLHC_Setup_InclBrl_4.py,InDetSLHC_Example/postInclude.DigitalClustering.py"
export preExecDetFlagsITk="DetFlags.ID_setOn();DetFlags.TRT_setOff();DetFlags.detdescr.TRT_setOff();DetFlags.makeRIO.TRT_setOff();DetFlags.BCM_setOff();DetFlags.detdescr.BCM_setOff();DetFlags.makeRIO.BCM_setOff();DetFlags.DBM_setOff();DetFlags.detdescr.DBM_setOff();DetFlags.makeRIO.DBM_setOff();DetFlags.Calo_setOff();DetFlags.Muon_setOff();DetFlags.Truth_setOn();DetFlags.simulate.TRT_setOff();DetFlags.simulate.BCM_setOff();DetFlags.simulate.DBM_setOff();"
export preExecGlobalFlagsITk="globalflags.DataSource.set_Value_and_Lock('geant4');"
export preExecSLHCFlagsITk="SLHC_Flags.doGMX.set_Value_and_Lock(True);SLHC_Flags.LayoutOption='InclinedDuals';"
export preExecRecFlagsITk="rec.doCalo.set_Value_and_Lock(False); rec.doMuon.set_Value_and_Lock(False);rec.doJetMissingETTag.set_Value_and_Lock(False);rec.doEgamma.set_Value_and_Lock(False);rec.doMuonCombined.set_Value_and_Lock(False);rec.doTau.set_Value_and_Lock(False); rec.doTrigger.set_Value_and_Lock(False); rec.doTagRawSummary.set_Value_and_Lock(False);"
export preIncludeITk="InDetSLHC_Example/preInclude.SLHC_Setup_InclBrl_4.py,InDetSLHC_Example/preInclude.SLHC_Setup_Strip_GMX.py,InDetSLHC_Example/preInclude.SLHC.py,InDetSLHC_Example/preInclude.SLHC.Reco.py,InDetSLHC_Example/SLHC_Setup_Reco_TrackingGeometry_GMX.py"
export postExecITk="ToolSvc.InDetSCT_ClusteringTool.useRowInformation=True;"
export conditionsITk="default:OFLCOND-MC15c-SDR-14-03"
export geometryITk="ATLAS-P2-ITK-20-00-00"
